services:
  postgres:
    image: postgres:16
    container_name: sql-with-postgres # it's just for docker desktop
    environment:
      POSTGRES_DB: sql_learning
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
